### ISSUE TITLE
PLib 2.20 Unresolved assembly reference not allowed

### ISSUE THREAD

**Issue by julian-perge** [peterhaneve/ONIMods#20]
Hello, not quite sure this error is coming up, but I don't receive this error in 2.19.

PLib 2.20
```
An exception occurred during merging:
1>  Unresolved assembly reference not allowed: UnityEngine.ImageConversionModule.
1>     at System.Compiler.Ir2md.GetAssemblyRefIndex(AssemblyNode assembly)
1>     at System.Compiler.Ir2md.GetTypeRefIndex(TypeNode type)
1>     at System.Compiler.Ir2md.VisitReferencedType(TypeNode type)
1>     at System.Compiler.Ir2md.GetMemberRefIndex(Member m)
1>     at System.Compiler.Ir2md.GetMethodToken(Method m)
1>     at System.Compiler.Ir2md.VisitMethodCall(MethodCall call)
1>     at System.Compiler.Ir2md.Visit(Node node)
1>     at System.Compiler.Ir2md.VisitExpression(Expression expression)
1>     at System.Compiler.Ir2md.Visit(Node node)
1>     at System.Compiler.Ir2md.VisitExpressionStatement(ExpressionStatement statement)
1>     at System.Compiler.Ir2md.Visit(Node node)
1>     at System.Compiler.Ir2md.VisitBlock(Block block)
1>     at System.Compiler.Ir2md.Visit(Node node)
1>     at System.Compiler.Ir2md.VisitBlock(Block block)
1>     at System.Compiler.Ir2md.VisitMethodBody(Method method)
1>     at System.Compiler.Ir2md.VisitMethod(Method method)
1>     at System.Compiler.Ir2md.Visit(Node node)
1>     at System.Compiler.Ir2md.VisitClass(Class Class)
1>     at System.Compiler.Ir2md.Visit(Node node)
1>     at System.Compiler.Ir2md.VisitModule(Module module)
1>     at System.Compiler.Ir2md.SetupMetadataWriter(String debugSymbolsLocation)
1>     at System.Compiler.Ir2md.WritePE(Module module, String debugSymbolsLocation, BinaryWriter writer)
1>     at System.Compiler.Writer.WritePE(String location, Boolean writeDebugSymbols, Module module, Boolean delaySign, String keyFileName, String keyName)
1>     at System.Compiler.Writer.WritePE(CompilerParameters compilerParameters, Module module)
1>     at System.Compiler.Module.WriteModule(String location, CompilerParameters options)
1>     at ILMerging.ILMerge.Merge()
1>     at ILMerging.ILMerge.Main(String[] args)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(5185,5): error MSB3073: The command ""C:\DEVELOPER\ONI-Mods\src\packages\ILMerge.3.0.29\build\..\tools\net452\ILMerge.exe" /ndebug /out:IncreasedResearchStorageMerged.dll IncreasedResearchStorage.dll PLib.dll /targetplatform:v2,C:/Windows/Microsoft.NET/Framework64/v2.0.50727" exited with code 1.
```

PLib 2.19
```
1>------ Rebuild All started: Project: IncreasedResearchStorage, Configuration: Debug Any CPU ------
1>  IncreasedResearchStorage -> C:\DEVELOPER\ONI-Mods\src\IncreasedResearchStorage\IncreasedResearchStorage.dll
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========
```

**Comment by julian-perge** [comment]
Disregard this as I had a massive brainfart.
